name: E2E Test
on: 
  schedule:
    - cron: '0 0 * * *'
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        record: ["record", "no-record"]
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm run start:app
          wait-on: 'http://localhost:3000'
          browser: "Replay Chromium"
          wait-on-timeout: 120
        env:
          RECORD_ALL_CONTENT: 1
          RECORD_REPLAY_METADATA_FILE: /tmp/replay-metadata
          RECORD_REPLAY_NO_RECORD: ${{ matrix.record == 'no-record' && '1' || '' }} 
      - name: Upload replays
        if: ${{ always() }}
        uses: replayio/action-upload@v0.4.3
        with:
          api-key: rwk_xxNF2q8coRNanmtYmhmzyvHZM7KQ2VvW8CuMGJwhPUJ
