name: E2E Test
on: 
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

jobs:
  cypress-record:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm run start:app
          wait-on: 'http://localhost:3000'
          browser: "Replay Chromium"
          wait-on-timeout: 120
        env:
          RECORD_ALL_CONTENT: 1
          RECORD_REPLAY_METADATA_FILE: /tmp/replay-metadata
          RECORD_REPLAY_TEST_METRICS: 1
          RECORD_REPLAY_WEBHOOK_URL: ${{ secrets.RECORD_REPLAY_WEBHOOK_URL }}
      - name: Upload replays
        if: ${{ always() }}
        uses: replayio/action-upload@v0.4.3
        with:
          api-key: rwk_xxNF2q8coRNanmtYmhmzyvHZM7KQ2VvW8CuMGJwhPUJ
          public: true
  cypress-no-record:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm run start:app
          wait-on: 'http://localhost:3000'
          browser: "Replay Chromium"
          wait-on-timeout: 120
        env:
          RECORD_ALL_CONTENT: 1
          RECORD_REPLAY_METADATA_FILE: /tmp/replay-metadata
          RECORD_REPLAY_DRIVER: /tmp/not-here
          RECORD_REPLAY_TEST_METRICS: 1
          RECORD_REPLAY_WEBHOOK_URL: ${{ secrets.RECORD_REPLAY_WEBHOOK_URL }}
  cypress-original:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm run start:app
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120